name = "BeamTracking"
uuid = "8ef5c10a-4ca3-437f-8af5-b84d8af36df0"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "0.3.6"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AtomicAndPhysicalConstants = "5c0d271c-5419-4163-b387-496237733d8b"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
SIMDMathFunctions = "d22a7203-ad50-4fbc-abc4-d6ac724cca58"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
Beamlines = "5bb90b03-0719-46b8-8ce4-1ef3afd3cd4b"

[extensions]
BeamTrackingBeamlinesExt = "Beamlines"

[compat]
Accessors = "0.1.42"
Adapt = "4.3.0"
AtomicAndPhysicalConstants = "0.8.0"
Beamlines = "0.6.4"
GTPSA = "1.4"
HostCPUFeatures = "0.1"
KernelAbstractions = "0.9.35"
MacroTools = "0.5.16"
Random = "1.10.10"
ReferenceFrameRotations = "3"
SIMD = "3.7.1"
SIMDMathFunctions = "0.1.3"
SpecialFunctions = "2.5.1"
StaticArrays = "1"
Unrolled = "0.1.5"
julia = "1.9"

[extras]
Beamlines = "5bb90b03-0719-46b8-8ce4-1ef3afd3cd4b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributions", "JET", "GTPSA", "BenchmarkTools", "Beamlines", "StaticArrays"]
